CNNModel:
  embed_dim: 128
  filter_sizes:
    - 3
    - 4
    - 5
  num_filters:
    - 64
    - 128
    - 256
  num_classes: 3
  dropout: 0.5

LSTMTextClassifier:
  n_layers: 6
  bidirectional: true
  dropout: 0.5
  embedding_dim: 128
  hidden_dim: 128
  output_dim: 3
  
MLPClassifier:
  num_classes: 3
  hidden_size: 2048
  input_dim: 128
  
LSTMMultiHeadAttention:
  num_layers: 6
  bidirectional: true
  num_heads: 8
  dropout: 0.5
  input_dim: 128
  hidden_dim: 128
  output_dim: 3